=== arlequinte/electre-drama_xml-tei_xslt_html/DTD_electre_giraudoux.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT ns1:TEI (ns1:teiHeader,ns1:text)>
<!ATTLIST ns1:TEI
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:teiHeader (ns1:fileDesc,ns1:profileDesc)>
<!ATTLIST ns1:teiHeader
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:text (ns1:front,ns1:body)>
<!ATTLIST ns1:text
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:fileDesc (ns1:titleStmt,ns1:editionStmt,
                        ns1:publicationStmt,ns1:sourceDesc)>
<!ATTLIST ns1:fileDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:profileDesc (ns1:langUsage,ns1:textDesc,ns1:particDesc)>
<!ATTLIST ns1:profileDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:front (ns1:docTitle,ns1:set)>
<!ATTLIST ns1:front
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:body (ns1:div1)+>
<!ATTLIST ns1:body
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:titleStmt (ns1:title,ns1:author)>
<!ATTLIST ns1:titleStmt
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:editionStmt (ns1:p)>
<!ATTLIST ns1:editionStmt
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:publicationStmt (ns1:publisher,ns1:date)>
<!ATTLIST ns1:publicationStmt
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:sourceDesc (ns1:bibl)+>
<!ATTLIST ns1:sourceDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:langUsage (ns1:language)>
<!ATTLIST ns1:langUsage
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:textDesc (ns1:domain,ns1:factuality,ns1:derivation,ns1:interaction,
                        ns1:purpose)+>
<!ATTLIST ns1:textDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:particDesc (ns1:listPerson)>
<!ATTLIST ns1:particDesc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:docTitle (ns1:titlePart)>
<!ATTLIST ns1:docTitle
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:set (ns1:p)>
<!ATTLIST ns1:set
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:div1 (ns1:head,ns1:div2+)>
<!ATTLIST ns1:div1
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  n CDATA #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:bibl (ns1:distributor
                    |(ns1:title,ns1:author,ns1:publisher,ns1:date,
                      ns1:idno))>
<!ATTLIST ns1:bibl
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:language (#PCDATA)>
<!ATTLIST ns1:language
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ident NMTOKEN #REQUIRED>

<!ELEMENT ns1:derivation EMPTY>
<!ATTLIST ns1:derivation
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:domain EMPTY>
<!ATTLIST ns1:domain
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:factuality EMPTY>
<!ATTLIST ns1:factuality
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>
  
  <!ELEMENT ns1:interaction EMPTY>
  <!ATTLIST ns1:interaction
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:purpose EMPTY>
<!ATTLIST ns1:purpose
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  degree NMTOKEN #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:listPerson ((ns1:person|ns1:personGrp)+,ns1:listRelation)>
<!ATTLIST ns1:listPerson
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:titlePart (#PCDATA|ns1:lb)*>
<!ATTLIST ns1:titlePart
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:div2 (ns1:head,ns1:castList?,
                    (ns1:note|ns1:stage|ns1:sp)+)>
<!ATTLIST ns1:div2
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ana CDATA #REQUIRED
  decls NMTOKEN #IMPLIED
  n CDATA #REQUIRED
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:distributor EMPTY>
<!ATTLIST ns1:distributor
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  facs CDATA #REQUIRED>

<!ELEMENT ns1:idno (#PCDATA)>
<!ATTLIST ns1:idno
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  type NMTOKEN #REQUIRED>

<!ELEMENT ns1:person (ns1:persName,ns1:note?)>
<!ATTLIST ns1:person
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  xml:id NMTOKEN #REQUIRED>

<!ELEMENT ns1:personGrp (ns1:persName)>
<!ATTLIST ns1:personGrp
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:listRelation (ns1:relation)+>
<!ATTLIST ns1:listRelation
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:castList (ns1:castItem)+>
<!ATTLIST ns1:castList
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:sp (ns1:speaker,ns1:stage?,ns1:p)>
<!ATTLIST ns1:sp
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  toWhom CDATA #IMPLIED
  who CDATA #REQUIRED>

<!ELEMENT ns1:relation EMPTY>
<!ATTLIST ns1:relation
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  active CDATA #IMPLIED
  mutual CDATA #IMPLIED
  name NMTOKEN #REQUIRED
  passive CDATA #IMPLIED>

<!ELEMENT ns1:castItem (#PCDATA)>
<!ATTLIST ns1:castItem
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:speaker (#PCDATA)>
<!ATTLIST ns1:speaker
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  rend NMTOKEN #REQUIRED>

<!ELEMENT ns1:title (#PCDATA)>
<!ATTLIST ns1:title
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:author (#PCDATA)>
<!ATTLIST ns1:author
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  key CDATA #IMPLIED
  ref CDATA #IMPLIED>

<!ELEMENT ns1:p (#PCDATA|ns1:emph|ns1:pc|ns1:persName|ns1:persPronouns
                 |ns1:said|ns1:seg|ns1:w|ns1:q)*>
<!ATTLIST ns1:p
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  decls NMTOKEN #IMPLIED>

<!ELEMENT ns1:q (#PCDATA|ns1:emph|ns1:lb|ns1:pc|ns1:persName
                 |ns1:persPronouns|ns1:said|ns1:seg|ns1:w)*>
<!ATTLIST ns1:q
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ana NMTOKEN #IMPLIED
  rend NMTOKEN #REQUIRED>

<!ELEMENT ns1:publisher (#PCDATA)>
<!ATTLIST ns1:publisher
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:date (#PCDATA)>
<!ATTLIST ns1:date
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  when-iso CDATA #REQUIRED>

<!ELEMENT ns1:persName (#PCDATA|ns1:emph|ns1:pc|ns1:persName
                        |ns1:persPronouns|ns1:w)*>
<!ATTLIST ns1:persName
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ref CDATA #IMPLIED
  type NMTOKEN #IMPLIED>

<!ELEMENT ns1:note (#PCDATA|ns1:ref|ns1:span)*>
<!ATTLIST ns1:note
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:ref EMPTY>
<!ATTLIST ns1:ref
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  target CDATA #REQUIRED>

<!ELEMENT ns1:span (#PCDATA)>
<!ATTLIST ns1:span
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  rend NMTOKEN #REQUIRED>

<!ELEMENT ns1:lb EMPTY>
<!ATTLIST ns1:lb
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'>

<!ELEMENT ns1:head (#PCDATA)>
<!ATTLIST ns1:head
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  rend NMTOKEN #IMPLIED>

<!ELEMENT ns1:stage (#PCDATA)>
<!ATTLIST ns1:stage
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  rend NMTOKEN #IMPLIED>

<!ELEMENT ns1:said (#PCDATA|ns1:emph|ns1:lb|ns1:pc|ns1:persName
                    |ns1:persPronouns|ns1:seg|ns1:w)*>
<!ATTLIST ns1:said
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ana NMTOKEN #REQUIRED
  who CDATA #REQUIRED>

<!ELEMENT ns1:emph (#PCDATA|ns1:emph|ns1:persName|ns1:persPronouns
                    |ns1:seg|ns1:w)*>
<!ATTLIST ns1:emph
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  corresp CDATA #IMPLIED
  xml:id NMTOKEN #IMPLIED>

<!ELEMENT ns1:seg (#PCDATA|ns1:emph|ns1:pc|ns1:persName|ns1:persPronouns
                   |ns1:said|ns1:seg|ns1:w)*>
<!ATTLIST ns1:seg
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ana NMTOKEN #REQUIRED>

<!ELEMENT ns1:w (#PCDATA)>
<!ATTLIST ns1:w
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ana NMTOKEN #IMPLIED
  corresp CDATA #IMPLIED
  function NMTOKEN #IMPLIED
  type NMTOKEN #IMPLIED>

<!ELEMENT ns1:persPronouns (#PCDATA)>
<!ATTLIST ns1:persPronouns
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  corresp CDATA #IMPLIED>

<!ELEMENT ns1:pc (#PCDATA)>
<!ATTLIST ns1:pc
  xmlns:ns1 CDATA #FIXED 'http://www.tei-c.org/ns/1.0'
  ana NMTOKEN #IMPLIED
  function NMTOKEN #IMPLIED
  type NMTOKEN #IMPLIED>
  
  <!-- Les entités sont classées par fonction et par ordre d'apparition. -->

<!ENTITY phr "périphrase">
<!ENTITY pn "prénom">
    
<!ENTITY ind "discours_indirect">
<!ENTITY dir "discours_direct">
<!ENTITY lib "dicours_indirect_libre">

<!ENTITY p1 "indicatif:présent">
<!ENTITY i1 "indicatif:imparfait">
<!ENTITY fs1 "indicatif:futur_simple">
<!ENTITY fp1 "indicatif:futur_proche">
<!ENTITY fa1 "indicatif:futur_antérieur">
<!ENTITY ps1 "indicatif:passé_simple">
<!ENTITY pc1 "indicatif:passé_composé">
<!ENTITY pp1 "indicatif:plus_que_parfait">
<!ENTITY imp "impératif">
<!ENTITY p2 "subjonctif:présent">
<!ENTITY ps2 "subjonctif:passé_simple">
<!ENTITY i2 "subjonctif:imparfait">
<!ENTITY p3 "conditionnel:présent">
<!ENTITY ps3 "conditionnel:passé">

<!ENTITY ac "actualité">
<!ENTITY hab "habitude" >
<!ENTITY gen "généralité">
<!ENTITY hyp "hypothèse">
<!ENTITY poss "possible_immédiat">
<!ENTITY pred "prédiction_certaine">
<!ENTITY evm "événement_récent">
<!ENTITY desc "description">
<!ENTITY ac2 "action_secondaire">
<!ENTITY ac1 "action_premier_plan">
<!ENTITY ac3 "action_irréversible">
<!ENTITY rec "récit_épique">
<!ENTITY csl "conseil">
<!ENTITY od "ordre">
<!ENTITY cnt "amorce_conte">
<!ENTITY cert "certitude">
<!ENTITY sh "souhait">
<!ENTITY irr "irréel_du_passé">

<!ENTITY exc "exclamation">
<!ENTITY int "question" >
<!ENTITY ssp "suspension">

<!ENTITY ett "excitation">
<!ENTITY irt "irritation">
<!ENTITY const "consternation" >
<!ENTITY rll "raillerie" >
<!ENTITY desv "désinvolture">
<!ENTITY aut "autorité" >
<!ENTITY attd "attendrissement">
<!ENTITY enq "enquête" >
<!ENTITY rh "rhétorique" >

<!ENTITY bt "beauté">
<!ENTITY tps "temps" >
<!ENTITY stat "statut_royal">
<!ENTITY ld "laideur">
<!ENTITY fl "folie">
<!ENTITY bst "bestiaire">
<!ENTITY de "deuil">
<!ENTITY tdr "tendresse">
<!ENTITY vl "violence">
<!ENTITY px "paix">
<!ENTITY vt "vertu">
<!ENTITY dmn "damnation">

=== arlequinte/electre-drama_xml-tei_xslt_html/TEI_electre_giraudoux.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-model href="ODD_electre_giraudoux.rng" lang="fr" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="ODD_electre_giraudoux.rng" lang="fr" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>

<!DOCTYPE ns1:TEI SYSTEM "DTD_electre_giraudoux.dtd">
<?xml-stylesheet type="text/xsl" href="electre_stylesheet.xsl"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">

 <teiHeader>

  <fileDesc>
   <titleStmt>
    <title>Électre</title>
    <author key="Jean Giraudoux (1882-1944)" ref="https://isni.org/isni/000000012117821X">Jean Giraudoux</author>
   </titleStmt>
     
   <editionStmt><p>Encodage ludique par Anne Bugner, pour le master TNAH de l'école des Chartes, année 2023.</p></editionStmt>

   <publicationStmt>
    <publisher>Éditions Bernard Grasset</publisher>
    <date when-iso="1937">1937</date></publicationStmt>

   <sourceDesc>
    <bibl>
     <title>Électre</title>
      <author>Jean Giraudoux</author>
      <publisher>Librairie Générale Française</publisher>
      <date when-iso="1987">1987</date>
      <idno type="ISBN">978-2-253-00129-4</idno>
    
     </bibl>
     <bibl><distributor facs="https://fr.wikisource.org/wiki/%C3%89lectre_(Giraudoux)"/></bibl>
    </sourceDesc>
   </fileDesc>

   <profileDesc>
    <langUsage>
     <language ident="fr">French</language></langUsage>

   <textDesc>
     <domain type="art"/> 
     <factuality type="fiction"/>      
    <derivation type="réécriture"/>    
    <interaction type="partial" active="singular" passive="world"/>  
    <purpose type="distrayant" degree="high"/>
    <purpose type="instructif" degree="high"/>
    <purpose type="déprimant" degree="medium"/>  

   </textDesc>

   <particDesc>
    <listPerson type="fictional">
              
               <!-- Premier groupe: personnages canoniques issus de la littérature grecque classique -->
     <person xml:id="el">
      <persName>Électre</persName></person>
     <person xml:id="o">
       <persName>Oreste</persName></person>
     <person xml:id="cly">
      <persName>Clytemnestre</persName></person>
     <person xml:id="eg">
      <persName>Égisthe</persName></person>
     <person xml:id="em1">
      <persName>Première Euménide</persName></person>
     <person xml:id="em2">
      <persName>Deuxième Euménide</persName></person>
     <person xml:id="emd3">
      <persName>Troisième Euménide</persName></person>
     <person xml:id="jd">
      <persName>Le Jardinier</persName>
     <note>
       La tragédie d'inspiration, celle d'Euripide, présentait le personnage du Laboureur, à qui Égisthe marie Électre pour l'éloigner du palais.
     </note></person>
               

               <!-- Personnages non actants dans nos extraits, mais mentionnés -->
     <person xml:id="agm">
      <persName>Agamemnon</persName></person>
     <person xml:id="atree">
      <persName>Atrée</persName></person>
     <person xml:id="thyeste">
      <persName>Thyeste</persName></person>
     <person xml:id="chrysothemis">
      <persName>Chrysothémis</persName></person>
     <person xml:id="cassandre">
      <persName>Cassandre</persName></person>

               <!-- Second groupe: ajouts propres à Giraudoux -->
     <person xml:id="mdt">
      <persName>Le Mendiant</persName></person>
     <person xml:id="fns">
      <persName>La Femme Narsès</persName></person>
      
              <!-- Enfin, puisqu'il en est question plusieurs fois dans notre texte -->
     <person xml:id="abd"><persName>anybody</persName><note>Expression du collectif: tout le monde, et personne en particulier. 
      Peut également désigner, par effet de mise en abyme et d'ironie tragique, le public.</note></person>

    <listRelation>
                  <!-- La famille d'Électre, les Atrides, dans la pièce -->
     <relation name="adelphes" mutual="#el #o #chrysothemis"/>
     <relation name="mère" active="#cly" passive="#el #o #chrysothemis"/>
     <relation name="père" active="#agm" passive="#el #o #chrysothemis"/>
     <relation name="époux" mutual="#cly #agm"/>
     <relation name="fiancés" mutual="#el #jd"/>
                 
                  <!-- Le passif des parents d'Électre : le meurtre d'Agamemnon -->
     <relation name="haine" active="#cly" passive="#agm"/>
     <relation name="amants" mutual="#cly #eg"/>
     <relation name="amants" mutual="#agm #cassandre"/>
     <relation name="meurtriers" active="#cly #eg" passive="#agm"/>
     <relation name="meurtriers" active="#cly #eg" passive="#cassandre"/>
   
                  <!-- Le passif de la famille paternelle d'Électre: la malédiction des Atrides -->
     <relation name="adelphes" mutual="#atree #thyeste"/>
     <relation name="haine" mutual="#atree #thyeste"/>
     <relation name="tortionnaires" active="#em1 #em2 #em3" passive="#atree #thyeste"/>
     <relation name="père" active="#atree" passive="#agm"/>
     <relation name="père" active="#thyeste" passive="#eg"/>
                
                  <!-- Les sentiments des uns pour les autres dans la pièce -->         
     <relation name="haine" active="#el" passive="#cly"/>
     <relation name="attirance_cachée" active="#jd" passive="#el"/>
     <relation name="attirance_cachée" active="#eg" passive="#el"/>
     <relation name="amour_très_freudien" active="#el" passive="#agm #o"/>
     <relation name="affection" mutual="#mdt #el; #o"/>
     <relation name="affection" mutual="#mdt #fns"/>
     <relation name="affection" mutual="#fns #el"/>
     <relation name="mépris" active="#em1 #em2 #em3" passive="#o"/>
     <relation name="mépris" active="#em1 #em2 #em3" passive="#el"/>  
    </listRelation>
   </listPerson>
  </particDesc>
 </profileDesc>
</teiHeader>

<text>
 <front>
  <docTitle>
   <titlePart>Électre<lb/>
              Pièce en deux actes
   </titlePart></docTitle>    
   <set><p>Cour intérieure dans le palais d'Agamemnon.</p></set>
  </front>

  <body>
   <div1 type="act" n="1">
    <head>ACTE I</head>


    <div2 type="scene" n="1" ana="Scène_d'exposition" decls="dialogues">
     <head>Scène I</head>

     <stage type="entrance">Un étranger (Oreste) entre escorté de trois petites filles, au moment où, de l’autre côté, arrivent 
            le jardinier, en costume de fête, et les invités villageois.</stage>
               
     <sp who="#em1" toWhom="#abd">
      <speaker rend="sc">Première petite fille.</speaker>
      <p><seg ana="enallage">Ce qu’<persPronouns corresp="#jd">il</persPronouns> <w type="&p1;" function="&desc;">est</w> <emph xml:id="beauté">beau</emph>, <persName ref="#jd" type="&phr;">le jardinier</persName> <pc type="&exc;" ana="&ett;">!</pc></seg></p></sp>
               
     <sp who="#em2" toWhom="#em1">
      <speaker rend="sc">Deuxième petite fille.</speaker>
      <p><seg ana="enallage"><persPronouns corresp="#em1">Tu</persPronouns> <w type="&p1;" function="&ac;">penses</w> <pc type="&exc;" ana="&ett;">!</pc></seg> C’<w type="&p1;" function="&ac;">est</w> <emph xml:id="temps">le jour de</emph> son <emph corresp="#&bt;">mariage</emph>.</p></sp>
               
     <sp who="#em3" toWhom="#o">
      <speaker rend="sc">Troisième petite fille.</speaker>
      <p>Le <emph corresp="#&tps;">voilà</emph>, <persName ref="#o" type="&phr;">monsieur</persName>, votre <emph xml:id="statut_royal">palais</emph> d’<persName ref="#agm" type="&pn;">Agamemnon</persName><pc type="&exc;" ana="&ett;">!</pc></p></sp>
       
     <sp who="#o" toWhom="#em1 #em2 #em3">
      <speaker rend="sc">L'Étranger.</speaker>
      <p><emph xml:id="laideur">Curieuse</emph> façade <pc type="&exc;" ana="surprise">!</pc><pc type="&ssp;" ana="&desv;">…</pc>  Elle <w type="&p1;" function="&ac;">est</w> d’aplomb <pc type="&int;" ana="&rh;">?</pc></p></sp>
       
     <sp who="#em1" toWhom="#o">
      <speaker rend="sc">Première petite fille.</speaker>
      <p><seg ana="prétérition">Non. Le côté droit <w type="&p1;" function="&hab;">n’existe</w> pas. <persPronouns corresp="#abd">On</persPronouns> <w type="&p1;" function="&hab;">croit</w> le voir, mais c’<w type="&p1;" function="&hab;">est</w> un <emph xml:id="folie">mirage</emph>. C’<w type="&p1;" function="&hab;">est</w> comme le jardinier qui <w type="&p1;" function="&ac;">vient</w> là, qui <w type="&p1;" function="&ac;">veut</w> <persPronouns corresp="#o">vous</persPronouns> parler. <persPronouns corresp="#jd">Il</persPronouns> ne <w type="&p1;" function="&ac;">vient</w> pas. <persPronouns corresp="#jd">Il</persPronouns> ne <w type="&fp1;" function="&poss;">va pas pouvoir</w> dire un mot.</seg></p></sp>
             
      <sp who="#em2" toWhom="#o">
      <speaker rend="sc">Deuxième petite fille.</speaker>
      <p>Ou <persPronouns corresp="#jd">il</persPronouns> <emph xml:id="bestiaire" corresp="#&ld;"> <w type="&fp1;" function="&poss;">va braire</w></emph>. Ou <emph corresp="#&bst; #&ld;">miauler</emph>.</p></sp>
       
     <sp who="#jd" toWhom="#o">
      <speaker rend="sc">Le Jardinier.</speaker>
